model_name: ae_hidden
encoder: hierarchicalencoderhidden
encoderblock: AtlasNew
decoder: decoderfullgeoatlasnew

output_smoothing_fct: 60
mse_weight: 0.5
coefficient: 0.01

hidden_layer: 1

loss_coeff:
  ae_loss: 1.0
  hit_loss: 1.0
  entropy: 0.01
  pos_energy: 1.0