model_name: autoencoderbase
encoder: hierarchicalencoder
encoderblock: AtlasNew
decoder: decoderfullgeoatlasnew

output_smoothing_fct: 60
mse_weight: 0.5
coefficient: 0.01

loss_coeff:
  ae_loss: 1.0
  kl_loss: 0.0
  hit_loss: 1.0
  entropy: 0.0
  pos_energy: 0.0
  neg_energy: 0.0
  logit_distance: 0.0