model_name: ae_separate
encoder: hierachicalencoder
encoderblock: AtlasNew
decoder: decoderfullgeoatlasnew

output_smoothing_fct: 60
mse_weight: 0.5
coefficient: 0.01

hidden_layer: 0
cond_p_size: 53
lin_bits: 19
sqrt_bits: 17
log_bits: 17

loss_coeff:
  ae_loss: 1.0
  hit_loss: 1.0
  mmd_loss: 30.0
  