model_name: autoencoderbase
encoder: hierachicalencoder
encoderblock: AtlasNew
decoder: decoderatlasnew

output_smoothing_fct: 60
mse_weight: 0.5
coefficient: 0.01

loss_coeff:
  ae_loss: 1.0
  hit_loss: 1.0
  entropy: 0.001
  pos_energy: 0.01