model_name: ae_separate
encoder: hierachicalencoder
encoderblock: AtlasNew
decoder: decoderfullgeoatlasnew

output_smoothing_fct: 60
mse_weight: 0.5
coefficient: 0.01

hidden_layer: 0

loss_coeff:
  ae_loss: 1.0
  hit_loss: 1.0
  entropy: 0
  pos_energy: 0