_target_: engine.engine.Engine
learning_rate: 0.0001

n_batches_log_train: 10
n_batches_log_val: 1

beta_gumbel_start: 1.0
beta_gumbel_epoch_start: 1
beta_gumbel_end: 100.0
beta_gumbel_epoch_end: 150  

slope_act_fct_start: 0.05
slope_act_fct_end: 0.

# train_vae_separate: 1
training_mode: ae