save_state: 1
load_state: 0
save_hists: 0
save_partition: 1
freeze_vae: 1

run_path: ""
# config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250821_230537-pp65hpwu/files/autoencoderhidden_9_config.yaml"
# config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250825_185123-cysb33l7/files/autoencoderhidden_9_config.yaml"
config_path: /fast_scratch_1/caloqvae/jtoledo/wandb/run-20250825_231749-qtzezvdq/files/autoencoderhidden_189_config.yaml
# config_path: /fast_scratch_1/caloqvae/jtoledo/wandb/run-20250819_203111-u88m8d6w/files/autoencoderbase_249_config.yaml

device: gpu
gpu_list:
  - 1

defaults:
  - data: CaloChallenge2
  - wandb: ML2
  - model: model3_calochallenge
  - engine: engine1
  - rbm: zephyr
  - _self_

n_epochs: 350
epoch_freeze: 250
epoch_start: 0