save_state: 1
load_state: 0
save_hists: 0
save_partition: 1
freeze_vae: 1

run_path: ""
config_path: /raid/javier/Projects/CaloQuVAE/wandb/run-20250812_134040-5u25xxd7/files/autoencoderbase_249_config.yaml

device: gpu
gpu_list:
  - 3

defaults:
  - data: CaloChallenge2_DGX
  - wandb: DGX
  - model: model3_calochallenge
  - engine: engine1
  - rbm: zephyr
  - _self_

n_epochs: 350
epoch_freeze: 350
epoch_start: 0