save_state: 1
load_state: 0
save_hists: 0
save_partition: 1
freeze_vae: 1

run_path: ""
config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250813_233227-z4hoj71e/files/autoencoderbase_249_config.yaml"

device: gpu
gpu_list:
  - 1

defaults:
  - data: CaloChallenge2
  - wandb: ML2
  - model: model3CA_calochallenge
  - engine: engine1
  - rbm: zephyr
  - _self_

n_epochs: 250
epoch_freeze: 200
epoch_start: 0