save_state: 1
load_state: 0
save_hists: 0
save_partition: 1
freeze_vae: 0

run_path: ""
# config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250821_230537-pp65hpwu/files/autoencoderhidden_9_config.yaml"
# config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250825_185123-cysb33l7/files/autoencoderhidden_9_config.yaml"
config_path: "/home/leozhu/CaloQuVAE/wandb-outputs/run-20251016_234041-uxt7g1zk/files/ae_separate_199_config.yaml"
# config_path: /fast_scratch_1/caloqvae/jtoledo/wandb/run-20250819_203111-u88m8d6w/files/autoencoderbase_249_config.yaml

device: gpu
gpu_list:
  - 3

defaults:
  - data: AtlasReg000New
  - wandb: ML2
  - model: model_ATLASNew_fullgeo_ae
  - engine: engine1
  - rbm: zephyr
  - _self_

n_epochs: 200
epoch_freeze: 250
epoch_start: 0