save_state: 1
load_state: 1
save_hists: 0
save_partition: 1
freeze_vae: 1

run_path: ""
# config_path: /home/jtoledo/CaloQuVAE/outputs_sym/run-20251108_201310-ltj5iz2k/files/ae_separate_39_config.yaml
config_path: /home/jtoledo/CaloQuVAE/outputs_sym/run-20251108_201310-ltj5iz2k/files/RBM_config_file.yaml

device: gpu
gpu_list:
  - 2

defaults:
  - data: AtlasReg000New
  # - data: AtlasCustom1
  - wandb: ML2
  - model: model_ATLASNew_fullgeo_ae
  - engine: engine1
  - rbm: zephyr
  - _self_

# - model: model_hidden_ATLASNew_fullgeo
n_epochs: 350
epoch_freeze: 250
epoch_start: 0

refactor_binary_energy: 1