save_state: 1
load_state: 1
save_hists: 0
save_partition: 1
freeze_vae: 1

run_path: ""
config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250821_230537-pp65hpwu/files/autoencoderhidden_9_config.yaml"

device: gpu
gpu_list:
  - 0

defaults:
  - data: AtlasReg035
  - wandb: ML2
  - model: model3_hidden_calochallenge
  - engine: engine1_hidden
  - rbm: zephyr
  - _self_

n_epochs: 350
epoch_freeze: 250
epoch_start: 0