model_name: Zephyr
fullyconnected: 1
no_weights: 0
latent_nodes_per_p: 46
partitions: 4
method: "CD"
bgs_steps: 3000
lr: 0.1
gamma: 0.001
w_std: 
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
b_std: 
  - 1.0
  - 1.0
  - 1.0
  - 1.0
optimize_partition: 0
hidden_layer: 0