model_name: Zephyr
fullyconnected: 0
latent_nodes_per_p: 302
partitions: 4
method: "CD"
bgs_steps: 3000
lr: 0.01
gamma: 0.001
w_std: 
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
b_std: 
  - 1.0
  - 1.0
  - 1.0
  - 1.0
optimize_partition: 0
hidden_layer: 1